{% set name = "chest" %}
{% set version = "0.2.3" %}
{% set sha256 = "f2d1030d4720fd4c0cb258c3383d4bab764cfe441bab1366a0d186b0baf4f4d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - heapdict

test:
  imports:
    - chest

about:
  home: https://github.com/ContinuumIO/chest
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Simple on-disk dictionary'
  description: |
    Chest acts like a dictionary but it can write its contents to disk.
    This is useful because Chest can then hold datasets that are larger than
    memory and Chest persists and so can be saved and loaded for later use.
  doc_url: https://pypi.python.org/pypi/chest/
  doc_source_url: https://github.com/blaze/chest/blob/master/README.rst
  dev_url: https://github.com/blaze/chest

extra:
  recipe-maintainers:
    - mrocklin
    - synapticarbors
