travis:
  secure:
    BINSTAR_TOKEN: uN84gKz+ov/L4dfJNLL0t4OsjSpOMKsZRLVplKeIrxUjKU6HUlXbi8jUfXGYblJmEVQKh1fE8Y1afmlBD0tp1lgYa2r4kXqVBs2o0bP5osrXj9s0UmkvSd0dXq3mwoAu/i/kfk0g114YGA01z5FS34XLqFRjEzirfvI2FftFBPYdim0GAOWxVp9Uws8wK31RzO/9Rz3WY+0StIv9nijvZcglupwYDGP0FmMpJKSKXqFYL0YzjjNy6deQShUYoeMP17VLYobht/bUmri31w+G0eiZVaqJ1Xf0/I32ltqgWpPLOw8xcLMJY8tmMge61xxC4Cc6q4uxQ89Nfh76XS9BDWJg5kQFIP3lPjhgjd7xkbCaKVN6Mx/Odd+sZNtUdeNr/hQGOo1udkMBHPVgdPEbcVpYlNF/BxXwpgy3Uu9nBBfSlqvyWJn8/j9wal0OtH3VtLywR+tFFiBqu6700i3UU6IGO1LwEioY1Bjv0/lpBVm+T58I7SQFaUfuEuu29hqXRvl5gDB9unJksILaTiaLHjCwpMw5Ql/tMKD8HYRObVkl5fDaL1nz7HKpZemd+sN38hYK2cG6d30exDTFn7Lwi+1gvJgVThh5/uek4pjHUKPNNnFj3s0Q/rcyhigMjim2GfbSUjfzIkQXFThzuPhmOv+Ya6JMoNGDwT6A5OlYTM4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
