travis:
  secure:
    BINSTAR_TOKEN: bxLtMyejUXPWjBrimwiltQJGZh27CG1IVq7tZ5Dh0DY5v2/UcjJ1GnPd49RAYl4xi+9Bh8JQ3iQgV4pq0QaWlnH2IWGTZ1YgnBFfnTwZRDbibKTbQYoPJCIxnkq5XDXWa+zffsV65gqFVIvqygg8s5cSFu8JbwgBRRnFGNAoTDJh8v08Do7jEBaRFN14cfYwkUbiBFWRMaGsWeqXs7n0orBKQFtm/2WViVgic369UjuZlLgPP7XRGYOcIb+Wppuz0o8X2EiiEyafrHBntjgNO5ZxrcFD3rB7d83l3qpjHYsNbHKmustXdhFsZO968kujTfTanHSKQZhwf+lCPXdix95OvWenBV1kzy77Jqvit9RKAl9DvF+FH4cMcu7oMGlIWJQ2+0b8S8OTgX7yw8w3e7NhVS1AVklR1zT771tCF46BfGYE1JjOtFmPSpC9gKq/W3snU86spvaU5ckzrpoY6nW/bkAuxAcgnoCRCxaDSl524nXm6v7ZyiEedF9US3iIvYmbVrh4iGMtV+/+hS4lrO+l6quM4db87EpkPMxgg14AQttXFYNzMMJYw9A22ZkR7v598HVncNfukIpF3RXEwTR+1oYcB3s961A3kIrSKnIxVZ4127riNZdEw6ulDjyVs+yCbzBSKUjE/2+afQCoKEEFvYE2oRwXVKOZzQP0a6I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
